const portfolioItems = [
	{
		id: 1,
		title: 'Brand Revolution',
		category: 'Branding',
		description: 'Complete brand identity redesign for a tech startup',
		image: '/gallery/IMG-20251008-WA0016.jpg',
		tags: ['Design', 'Strategy'],
	},
	{
		id: 2,
		title: 'Digital Campaign',
		category: 'Marketing',
		description: 'Multi-channel marketing campaign with 300% ROI',
		image: '/gallery/IMG-20251008-WA0017.jpg',
		tags: ['Marketing', 'Analytics'],
	},
	{
		id: 3,
		title: 'Social Media Presence',
		category: 'Social',
		description: 'Building a 100k+ follower community in 6 months',
		image: '/gallery/IMG-20251008-WA0030.jpg',
		tags: ['Social Media', 'Content'],
	},
	{
		id: 4,
		title: 'Product Launch',
		category: 'Advertising',
		description: 'Nationwide advertising campaign for product launch',
		image: '/gallery/IMG-20251008-WA0033.jpg',
		tags: ['Advertising', 'Video'],
	},
	{
		id: 5,
		title: 'Creative Workshop',
		category: 'Branding',
		description: 'Corporate identity and workspace branding',
		image: '/gallery/IMG-20251008-WA0041.jpg',
		tags: ['Branding', 'Design'],
	},
	{
		id: 6,
		title: 'E-commerce Growth',
		category: 'Marketing',
		description: 'SEO and PPC strategy driving 500% sales increase',
		image: '/gallery/IMG-20251008-WA0048.jpg',
		tags: ['SEO', 'Marketing'],
	},
    {
        id: 7,
        title: 'Signboard Advertising',
        category: 'Advertising',
        description: 'Captivating signboard designs that grab attention and drive foot traffic',
        image: '/gallery/IMG-20251008-WA0005.jpg',
        tags: ['Signboard', 'Design'],
    },
    {
        id: 8,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0011.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 9,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0007.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 10,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0008.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 11,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0009.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 12,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0010.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 13,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0012.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 14,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0013.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 15,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0014.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 16,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0015.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 17,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0018.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 18,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0019.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 19,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0020.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 20,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0021.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 21,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0022.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 22,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0023.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 23,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0024.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 24,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0025.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 25,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0026.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 26,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0027.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 27,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0028.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 28,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0029.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 29,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0031.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 30,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0032.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 31,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0034.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 32,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0035.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 33,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0036.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 34,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0037.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 35,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0038.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 36,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0039.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 37,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0040.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 38,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0042.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 39,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0043.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 40,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0044.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 41,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0045.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 42,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0046.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 43,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0047.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 44,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0049.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 45,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0050.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 46,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0051.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 47,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0052.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 48,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0053.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 49,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0054.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 50,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0055.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 51,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0056.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 52,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0057.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 53,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0058.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 54,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0059.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 55,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0060.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 56,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0061.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 57,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0062.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 58,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0063.jpg',
        tags: ['Event', 'Promotion'],
    },
    {
        id: 59,
        title: 'Event Promotion',
        category: 'Marketing',
        description: 'Successful event promotion leading to high attendance and engagement',
        image: '/gallery/IMG-20251008-WA0087.jpg',
        tags: ['Event', 'Promotion'],
    },

];

import { useEffect } from 'react';

export default function AllProjects() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <section className="py-12 md:py-24 bg-secondary/10 min-h-screen">
      <div className="container mx-auto px-4 sm:px-6">
        <h2 className="text-3xl sm:text-4xl md:text-5xl mb-8 md:mb-10 text-center">All Projects</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 md:gap-8">
          {portfolioItems.map((item) => (
            <div
              key={item.id}
              className="relative overflow-hidden rounded-2xl sm:rounded-3xl bg-card border border-border"
            >
              <div className="w-full aspect-[4/3] bg-gray-100">
                <img
                  src={item.image}
                  alt={item.title}
                  className="w-full h-full object-cover rounded-xl sm:rounded-2xl"
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}